### ISSUE TITLE
Support Page Article Improvements (polkadirk)

### ISSUE THREAD

**Issue by keeganquigley** [w3f/1KC#10]
Hi @polkadirk thanks for your interest in the 1KC program, moving the conversation here!

Please submit any ideas you have as a comment in this issue and we can move forward from there!

- Tasks
- [x] (5/per) Choose 3 support page articles and improve or fix errors. Based on these deliveries, we will review and workout next steps.

- To Do
- [x] Define support article improvement tasks

**Comment by emresurmeli** [comment]
@polkadirk I'll continue the convo here (via Discord). Go ahead and choose an existing support article to improve and/or fix errors on. Use this Google sheet to do your work on!
https://docs.google.com/document/d/152XFFT5-8kM5PFpHjZatGxNxH_nAR8UiLYe6oVMia8w/edit

**Comment by keeganquigley** [comment]
Hi @polkadirk, just curious as to whether you are still interested in submitting your task. No worries if you are still working on it, just give me an update here. It can just be one or two articles if you'd like, and then after it is approved we will create a new task for more articles. Let me know if you have any questions. Otherwise, we will close the issue after a few days of inactivity.

**Comment by polkadirk** [comment]
Hey @keeganquigley apologies for the delay. Have had a backlog on work to catch up on after returning home from Europe. This task is currently at the top of my to do list. Il have it completed before Monday morning next week. Christian

**Comment by polkadirk** [comment]
@keeganquigley @emresurmeli 
I have attached a google drive which contains suggested edits to 3 articles from the support page.

https://drive.google.com/drive/folders/19k7PFb9iVu5kh2ifJMRVQl4z-i5KEvop?usp=sharing

Overall - the grammar across the website (I reviewed about 10 articles) is very good. I only found a couple of cases of genuine errors (they are suggested as edits in the google docs). There is however a few common language uses that I would not recommend. For example:

- the use of aren't, you'd, you'll. I would not recommend using these terms in formal writing like support guides.
- Many sentences start with 'this' or similar phrases - this is generally avoided wherever possible.
Generally a publication will have a 'style guide' for these kind of things.

The larger issues with the articles is that they seem to be unclear for their intended audience. For example:
The 'where to buy DOT and KSM' seemingly would be intended for new users - the article however lacks information that would be needed for a genuine new user.
I also feel that more content aimed at onboarding users next to 0 blockchain knowledge may be beneficial.

Hope this was helpful!

Christian

**Comment by keeganquigley** [comment]
Thanks for your submission @polkadirk I have just a few comments/notes. First, I liked your improvements on the second article! They definitely help to improve tone and clarity. However, I am not seeing what edits you made on the first and third articles. Can you "suggest" edits rather than edit directly? Follow [these instructions](https://support.google.com/docs/answer/6033474?hl=en&co=GENIE.Platform%3DDesktop) to edit in "suggestion mode". We will be asking this for all submissions moving forward.

Regarding your other comments, they are very helpful. I agree we could remove contractions from articles. We also like your suggestion about creating a style guide, which I have started building to not only allow us to establish better guidelines, but also to help contributors understand the standards we already have in place. I should have this completed soon. For now, if you can revise your edits I will review them in order to move you along to the next stage. Thanks!

**Comment by polkadirk** [comment]
Hey Keegan! Apologies for the slow response - I have been away for the week. The articles I link have already included suggested edits. Though you may be unable to see them because of your permissions. Can you provide me your email? Il give you the correct permissions. Il also attach the files below.
Thats great about your progress with a style guide - I am currently in the process of creating one for OAK Network. Potentially we could collaborate?
If you have any free time I would love to jump on a quick call with you. 
[Where to store DOT_ Polkadot wallet options.docx](https://github.com/w3f/1KC/files/8752385/Where.to.store.DOT_.Polkadot.wallet.options.docx)
[How to participate in crowdloans.docx](https://github.com/w3f/1KC/files/8752391/How.to.participate.in.crowdloans.docx)

**Comment by keeganquigley** [comment]
Thanks for your response @polkadirk no worries! I just requested edit access on the docs so hopefully that will do the trick. You should be able to see my email address in the request. And yes, would love to collaborate! I'm happy to jump on a call; if you can email me back with your time zone, let's find a good time to meet up. Thanks!

**Comment by polkadirk** [comment]
Sure thing! I am in AEST timezone - if you have any availabilities your time around 5pm (EST) that would suit my calendar well but im pretty flexible. Do you have a calendly?

**Comment by keeganquigley** [comment]
@polkadirk I do! 5pm works for me, I just sent my Calendly link to your email. Thanks!

**Comment by polkadirk** [comment]
Thanks Keegan - I am in the US for consensus so am a little busy but will get to making some changes next weekend.

**Comment by emresurmeli** [comment]
@polkadirk Could you send us a Kusama address so we can send you the payout?

**Comment by polkadirk** [comment]
Hey there!

You can use this KSM address.

'Fy3xsUAyfHJoEZeD6aWLtbXCWarLJiojTY76EYFfRNBjZeH'

Please let me know if there are any issues

**Comment by polkadirk** [comment]
Just saw your eddit - do you want a Karura address instead of KSM?

Karura - 'rh1WpibHQXfjazReHrecJC55RScfQVvs6rtnLQ4SYw7RPra'

**Comment by polkadirk** [comment]
Hey @emresurmeli hope you're doing well.

any updates on this? do you need any more info from me?

**Comment by laboon** [comment]
@emresurmeli is on vacation - @DrW3RK can you take a look at this?

**Comment by polkadirk** [comment]
Hey Bill!

Im in no rush - happy to wait for Emre to finish vacation.

Best wishes,

Christian Dirk
OAK Network

**Comment by emresurmeli** [comment]
Hi @polkadirk, thank you for your contribution and patience! The Karura address works great.

**Comment by polkadirk** [comment]
Welcome back! @emresurmeli 

if you make a payment can you please send me the extrinsic ID so I can confirm I have received the funds?

**Comment by keeganquigley** [comment]
Thanks @polkadirk did you still wish to continue with more articles or should we go ahead and close this issue once payment is received?

**Comment by polkadirk** [comment]
Hey @keeganquigley - i have a little more free time at the moment so im happy to continue. Is there any specific articles that need reviewing or should i just pick any and send to you?

**Comment by keeganquigley** [comment]
Thanks @polkadirk, we are starting to release articles featuring the new [staking dashboard](https://staking.polkadot.network/dashboard/#/overview) if you want to look those over, otherwise feel free to pick any that you like!

**Comment by keeganquigley** [comment]
Closing for @Polkadirk, as he had some other things come up to take care of.
