### ISSUE TITLE
Support Page Article Improvements (P4tton / Trey)

### ISSUE THREAD

**Issue by emresurmeli** [w3f/1KC#9]
Hi @P4tton here is the issue where we can track the support tasks you will be working on!

- Tasks
- [x] (5) Remove all unnecessary bolding in this article: https://support.polkadot.network/support/solutions/articles/65000098878-how-to-create-a-dot-account

- [x] (5/per) Work to make the articles have a more uniform look. Right now, there is a high amount of contrast from one article to the next. Such as this article (https://support.polkadot.network/support/solutions/articles/65000180708-why-have-i-stopped-nominating-staking-limits-explained), very uniform and nice feeling.

**Comment by P4tton** [comment]
https://docs.google.com/document/d/1KN6wZ_6wL-1e8muFhdTWhYQXJsr8hHYtVwxj_kbsoBU/edit?usp=sharing here is the first iteration of edits.

**Comment by emresurmeli** [comment]
Requested access

**Comment by P4tton** [comment]
Just accepted!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by keeganquigley** [comment]
Thanks @P4tton I reviewed your submission and am happy to go ahead and accept it. I will implement these changes! I have added a new task below. Feel free to submit more and we will review them. Just as a reminder, the reward structure is based on the number of words fixed (for task #2).

- [ ] (5/per) Work to make the articles have a more uniform look. (Headers, font type, size, etc). Add pictures if necessary.

- [ ]  (5/per) Fix errors (grammatical, spelling, etc).

**Comment by keeganquigley** [comment]
Hi @P4tton just reaching out to see if you are still planning on submitting your tasks. No worries if you are still working on them, just looking for an update. Otherwise, we will close this issue after a few days of inactivity. Thanks.

**Comment by P4tton** [comment]
Yep! I am still working.

**Comment by P4tton** [comment]
Hello, something came up and I will not be able to finish the 2nd task. Sorry for the delay!

**Comment by keeganquigley** [comment]
Hi @P4tton no worries thanks for letting us know.
